### ISSUE TITLE
Add suspense to the 3 images on the blogs->creating pop-up screen.

### ISSUE THREAD

**Issue by Prathamkrishna** [Prathamkrishna/Prathamkrishna-website#2]
<img width="1440" alt="Screenshot 2021-10-04 at 2 19 00 PM" src="https://user-images.githubusercontent.com/34184758/135821491-a35faa52-0617-4ab1-b507-ab9cdd81e3b6.png">

Example^^
The image shows plain background until the image loads. So, I want a loading graphic/text to be displayed until the image loads.

Comment on this issue so we can discuss on the same and proceed:)

**Comment by fkashrafi** [comment]
I want to contribute to it can you assign me. please

**Comment by SanthoshM25** [comment]
I'm interested in contributing @Prathamkrishna

**Comment by Prathamkrishna** [comment]
Alright, I'll merge the PR that comes in first @fkashrafi @SanthoshM25  :)

P.S: if you can show a blurred preview of the image until it loads, that'd be great. But you can go ahead with a fancy normal loader as well.
