### ISSUE TITLE
Add Content

### ISSUE THREAD

**Issue by Prathamkrishna** [Prathamkrishna/Prathamkrishna-website#3]
Add Spring Boot content on my website: https://prathamkrishna.codes

```
I am a developer from India, primarily working on React Native, Spring Boot and PostgreSQL along with the related frameworks and libraries. I also love working with C++, Java and the cloud. Apart from my work life, I love exploring new music from a variety of genres; I have multiple organised playlists on Spotify! I also love travelling on my motorcycle whenever I need a break/time off.
```

<img width="949" alt="Screenshot 2022-01-12 at 11 48 45 AM" src="https://user-images.githubusercontent.com/34184758/149074481-ee47a441-39b9-4a67-b5e1-0457a8e04893.png">

Add PostgreSQL and IntellJ Idea section on the list:

```
PostgreSQL: My fav SQL DB client!
```

```
IntellJ Idea: Love using this IDE for java/maven development, makes everything a whole lot easier!
```

<img width="1073" alt="Screenshot 2022-01-12 at 11 52 37 AM" src="https://user-images.githubusercontent.com/34184758/149075070-41adead2-7376-4f25-b077-a343a562fa07.png">

Remove Visual Studio 2019.

Also, re-arrange the above section to:
-> Spring Boot
-> React Native
-> PostgreSQL
-> React
-> IntellJ Idea
-> VS code
-> Prettier
-> ExpressJS + MongoDB

**Comment by vijethx** [comment]
Added content

**Comment by vijethx** [comment]
- #4

**Comment by Prathamkrishna** [comment]
@vijethx finished it.
